language: java
jdk:
- oraclejdk8
before_install:
  - wget http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.2/bin/apache-tomcat-9.0.2.tar.gz
  - tar -xzvf apache-tomcat-9.0.2.tar.gz
  - export CATALINA_HOME=$TRAVIS_BUILD_DIR/apache-tomcat-9.0.2
  - wget http://bit.ly/2iPUBvf -O $CATALINA_HOME/conf/tomcat-users.xml
install: ant war
before_script:
  - tar -xzvpf $TRAVIS_BUILD_DIR/WebContent/WEB-INF/lib/jni/ubuntu64.tar.gz -C $TRAVIS_BUILD_DIR/WebContent/WEB-INF/lib/jni/
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/WebContent/WEB-INF/lib/jni/
script:
- ant test
- ant testWS
- cat log/*.txt
before_deploy:
  - rm -rf log/*
  - rm -rf apache-tomcat-9.0.2
  - find $TRAVIS_BUILD_DIR/WebContent/WEB-INF/lib/jni/ -type f ! -iname "*.tar.gz" -delete
deploy:
  provider: cloudfoundry
  api: https://api.eu-de.bluemix.net
  username:
    secure: LiMyuALJDmqtJfR+UrGNoj4b1xyibcVWI62q8LyrkDLVs1+XnNRIXv2cJnP0j9RZOnNicxZElQDNhokrdYFvjCEAn9cZFVAp+Dwk+mJu1ig3U8oNYuGyFECQU0uQ5NYM1xlzvKCNGS38CX7+6KUxkrDAzgXYe+XSD29Tdnz5e4KvBkjx9+LOKfPB8Q2171p18f55RHaz8wukEDCVsjdwi8kuhL5NACMwUmyMgfPf28mPPVFv8nfwNzRPNgLyz9n3ari5gvsSp9G3w3kKyQVb8Xg4mnoiAgoFwwlHTKqycFYE0kgSYb9GtvvhwDu8vtodFaJCxRR7vC6AvRHs3a8tcpF5DTiqOLdK2hS+lSv4nUC6d13HU9Eii2on85CHZQ1K3QPyh+NJ49kK3dqikFJdGwkzzg1uSgCXIgw700NjuIjubDpSZbpHh9AtXCtYpkl3xAmu1mSdAZjl9AEOng3VSB7YuUuiYVhP6v66K4gMU6w0dcK6ZECQv7h91HCPn3ZVwK+4vbDEwG0NKfth20lvB1Kz5JrVC0naNaz8NuRVEJsIvaBid2jFBU0S7UQx8snok5T7VFUogzD+j9xwlKJEyHeXanAqc85rEwaBcflDbmPgveIOJmlZbdmc1x/5EnFXQcjHWxxd4LDnILgWXR4EnL6tiX8ezyMRY8I1UR+iZvU=
  password:
    secure: eF9BWg9KuPaY/jJr6W0mHw62gOzeoOPO//8UDeldyC67JT7rJXUAW1cMgRzLZvo8iZGY9/m8fdXrleFcUyDApnrqj2N77GPwq/zLddTsRFGEsJBI+q7rYTAfA3sQvtGj0rwOFdIUyPGQizdyBkLvaJxP6i5SGDSPOnnsoCz8TY48QPNxP+XkhjFNPsDk67kAfVGfFessxM1WxcYQ0veGpIHA4cYZ4eZ2/hSr1xLtKB5Qk8esfmQ08SkBPkJHoR7u+2vNCHtlqTHQbChT7S+BGVleeQDFD/pOzKYtSl9+KeCtcBcVgQEhGrHbrj9dTEbz/NinpU139gsXrLmVMIfMDRaXfcA3D1rIKQKK0L/w8pruAlu+X9d5QbBt4Sz9H50xuar7YHJTPP8HFK6qDHuqVW/8dtDq4xdMlyujsj/ziBd9cttLF6LZTDIE4tRoXQGiAx2CtXlLyDnkc4oBJdIgRzCm1S8EcU2pESOBG3ISAYLmvFgUVBB5LBgyoo8aVFvvfNqbU1SqSp8YaNOibhxO3q/lk9wZo4sloWso7j9XtAY/uP3tZycvweN/asXNyFQS6BR/+BmWPKgUCic8bEKOJSDs8TmyWwKOfCbR0vRgUmMkQfJEp4eaHc2Fk2PZTmtq/XaoLGHRU0iG0TWz4qXx/45xfSQNXDuMTG+88ab0tCA=
  organization: raffysommy
  space: dev
  on:
    repo: raffysommy/verifoo
    branch: rest-service